from typing import Protocol, Any


class ProductRepository(Protocol):
    def next_platform_code(self) -> int: ...
    def insert_product(self, data: dict) -> dict: ...
    def insert_skus(self, rows: list[dict]) -> list[dict]: ...
    def get_product(self, product_id: str) -> dict | None: ...
    def update_product(self, product_id: str, patch: dict) -> dict: ...
    def list_active(self, limit: int, cursor: str | None) -> list[dict]: ...
