# .streamlit/secrets.toml
SUPABASE_URL = "https://ezjgnmbuheheytcyibmx.supabase.co"
SUPABASE_KEY = "sb_publishable_p5v312ic88RSaNBCyDJwbQ_PpAVDKYd"
BASE_URL = "http://localhost:8501/cue_sheet"
GEMINI_API_KEY = "AIzaSyAzroDUibfyNN7SxbM-yiqzy_w34TIWLhg"